######################################################
#                                                    #
# Lab 6: Gaussian mixture EM                         #
#                                                    #
# R/run_lab6.r                                       #
#                                                    #
# Read the datasets generated by R/gendata.r.        #
# Fit the mixture model from five starting values.   #
# Compare estimates and save likelihood plots.       #
#                                                    #
######################################################

source(file.path("R", "lab6.r"))

# Setup. Read the simulated data and use only x when fitting the model.
sample_sizes <- c(100L, 1000L, 10000L)
data_paths <- file.path("data-raw", paste0("mixture_n", sample_sizes, ".csv"))

if (!all(file.exists(data_paths))) {
  stop("Missing simulated data. Run source(file.path('R', 'gendata.r')) first.",
       call. = FALSE)
}

# Task 4. Five starting values for each sample size

# These starts do not use true labels, fitted parameters, or simulated counts.
starts <- data.frame(
  start = 1:5,
  pi1 = c(1 / 3, 0.2, 1 / 3, 0.5, 0.2),
  pi2 = c(1 / 3, 0.3, 1 / 3, 0.3, 0.5),
  pi3 = c(1 / 3, 0.5, 1 / 3, 0.2, 0.3),
  mu1 = c(-4, -2, -0.2, -5, 5),
  mu2 = c(-0.5, 1, 0, -3, 1),
  mu3 = c(5, 3, 0.2, -1, -2),
  variance = c(2, 4, 8, 2, 3)
)

comparison_rows <- list()
history_rows <- list()
datasets <- vector("list", length(sample_sizes))
fits <- vector("list", length(sample_sizes))
row <- 0L

# Use the functions from Tasks 1-3 to fit each dataset from all five starts.
for (i in seq_along(sample_sizes)) {
  n <- sample_sizes[i]
  data <- read.csv(data_paths[i])
  datasets[[i]] <- data
  fits[[i]] <- vector("list", nrow(starts))

  for (s in seq_len(nrow(starts))) {
    fit <- em_mixture(
      data$x,
      proportions = as.numeric(starts[s, c("pi1", "pi2", "pi3")]),
      means = as.numeric(starts[s, c("mu1", "mu2", "mu3")]),
      variance = starts$variance[s]
    )

    fits[[i]][[s]] <- fit
    gains <- diff(fit$history$loglik)
    row <- row + 1L

    comparison_rows[[row]] <- data.frame(
      n = n,
      start = s,
      pi1 = fit$proportions[1],
      pi2 = fit$proportions[2],
      pi3 = fit$proportions[3],
      mu1 = fit$means[1],
      mu2 = fit$means[2],
      mu3 = fit$means[3],
      variance = fit$variance,
      loglik = fit$loglik,
      iterations = fit$iter,
      converged = fit$converged,
      min_loglik_gain = min(gains),
      nondecreasing = all(gains >= -1e-8)
    )

    history_rows[[row]] <- data.frame(n = n, start = s, fit$history)
  }
}

# Compare likelihoods only among starts fitted to the same dataset.
comparison <- do.call(rbind, comparison_rows)
history <- do.call(rbind, history_rows)
comparison$loglik_gap <- ave(
  comparison$loglik,
  comparison$n,
  FUN = function(x) max(x) - x
)

stopifnot(
  all(comparison$converged),
  all(comparison$nondecreasing)
)

best_rows <- integer(length(sample_sizes))

for (i in seq_along(sample_sizes)) {
  candidates <- which(comparison$n == sample_sizes[i])
  best_rows[i] <- candidates[which.max(comparison$loglik[candidates])]
}

best <- comparison[best_rows, ]

# Save starting values, aligned estimates, and every likelihood history.
dir.create("results", showWarnings = FALSE)

write.csv(
  starts,
  file = file.path("results", "starting_values.csv"),
  row.names = FALSE
)

write.csv(
  comparison,
  file = file.path("results", "start_comparison.csv"),
  row.names = FALSE
)

write.csv(
  history,
  file = file.path("results", "loglik_history.csv"),
  row.names = FALSE
)

write.csv(
  best,
  file = file.path("results", "best_estimates.csv"),
  row.names = FALSE
)

# One page per n: a separate panel for every start avoids hidden overlapping lines.
save_loglik_plots <- function() {
  pdf(file.path("results", "loglik_history.pdf"), width = 11, height = 7.5)
  on.exit(dev.off(), add = TRUE)
  par(mfrow = c(2, 3), mar = c(4, 6, 3.5, 1), oma = c(0, 0, 2, 0),
      mgp = c(2.8, 0.7, 0), las = 1)
  for (i in seq_along(sample_sizes)) {
    for (s in seq_len(nrow(starts))) {
      fit <- fits[[i]][[s]]
      plot(fit$history$iteration, fit$history$loglik, type = "l", lwd = 2,
           col = "#0072B2", xlab = "Completed EM iteration",
           ylab = "", main = paste("Start", s), xaxt = "n", cex.axis = 0.85)
      axis(1, at = pretty(c(0, fit$iter), n = 4), cex.axis = 0.85)
      mtext("Observed-data log-likelihood", side = 2, line = 4.3, las = 0,
            cex = 0.8)
      mtext(sprintf("%d iterations | final = %.3f", fit$iter, fit$loglik),
            side = 3, line = 0.3, cex = 0.75)
    }
    plot.new()
    text(0, 0.92, "Reading the plots", adj = 0, font = 2, cex = 1.05)
    notes <- c("Iteration 0 is the initialization.", "Each panel uses its own axes.",
               "All five fits use the same data.", "Check every successive difference.",
               "Numerical tolerance: 1e-8.", "Convergence does not prove optimality.")
    text(0, seq(0.76, 0.16, length.out = length(notes)), notes, adj = 0, cex = 0.83)
    mtext(paste("Lab 6: observed-data log-likelihood | n =", sample_sizes[i]),
          outer = TRUE, font = 2, cex = 1.15)
  }
}

save_density_plots <- function() {
  pdf(file.path("results", "mixture_fits.pdf"), width = 11, height = 4.5)
  on.exit(dev.off(), add = TRUE)
  par(mfrow = c(1, 3), mar = c(4, 4, 3, 1), mgp = c(2.5, 0.7, 0), las = 1)
  for (i in seq_along(sample_sizes)) {
    x <- datasets[[i]]$x
    fit <- fits[[i]][[best$start[i]]]
    grid <- seq(min(x) - 0.5, max(x) + 0.5, length.out = 500L)
    fitted_density <- numeric(length(grid))
    truth <- numeric(length(grid))
    for (k in 1:3) {
      fitted_density <- fitted_density + fit$proportions[k] *
        dnorm(grid, fit$means[k], sqrt(fit$variance))
      truth <- truth + c(0.25, 0.5, 0.25)[k] * dnorm(grid, c(-3, 0, 4)[k], 1)
    }
    h <- hist(x, breaks = "FD", plot = FALSE)
    plot(h, freq = FALSE, col = "grey90", border = "white", xlab = "x",
         ylim = c(0, 1.15 * max(h$density, fitted_density, truth)),
         main = paste("n =", sample_sizes[i]))
    lines(grid, truth, col = "#D55E00", lwd = 2, lty = 2)
    lines(grid, fitted_density, col = "#0072B2", lwd = 2)
    legend("topright", c("True density", "Best of five"),
           col = c("#D55E00", "#0072B2"), lty = c(2, 1), lwd = 2,
           bty = "n", cex = 0.8)
  }
}

save_loglik_plots()
save_density_plots()

cat("Final estimates (components ordered by increasing fitted mean):\n")
print(comparison, row.names = FALSE, digits = 6)
cat("\nBest observed-data log-likelihood among five starts, within each n:\n")
print(best, row.names = FALSE, digits = 6)
cat("\nAll 15 fits converged; all histories are nondecreasing within 1e-8.\n")
cat("Saved four result CSVs and two PDF figures in results/.\n")
